name: QVNote Actions
on: [push]
jobs:
  Build-Binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      - name: Setup GoLang
        uses: actions/setup-go@v6
        with:
          go-version: '^1.27'

      - name: Setup ENV
        run: |
          export TAG_NAME=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          if [[ "$TAG_NAME" == "master" ]]; then export TAG_NAME=$(date +'%Y%m%d%H%M%S'); fi
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          npm i
          export CGO_ENABLED=0; go mod download

      - name: Lint frontend
        run: |
          npm run lint

      - name: Build frontend
        run: |
          npm run build

      - name: Building Linux binary
        run: |
          export CGO_ENABLED=0; export GOOS=linux; export GOARCH=amd64; go build -o qvnote-linux-x64 && chmod a+x qvnote-linux-x64

      - name: Building MacOS binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export CGO_ENABLED=0; export GOOS=darwin; export GOARCH=amd64; go build -o qvnote-mac-x64 && chmod a+x qvnote-mac-x64

      - name: Building Windows binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export CGO_ENABLED=0; export GOOS=windows; export GOARCH=amd64; go build -o qvnote-windows-x64.exe

      - name: Archiving
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          7z a -tzip qvnote-${{ env.TAG_NAME }}-linux-x64.zip notes qvnote-linux-x64
          7z a -tzip qvnote-${{ env.TAG_NAME }}-mac-x64.zip notes qvnote-mac-x64
          7z a -tzip qvnote-${{ env.TAG_NAME }}-win-x64.zip notes qvnote-windows-x64.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ env.TAG_NAME }}
          draft: true
          files: |
            qvnote-${{ env.TAG_NAME }}-linux-x64.zip
            qvnote-${{ env.TAG_NAME }}-mac-x64.zip
            qvnote-${{ env.TAG_NAME }}-win-x64.zip


